"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./answer-version"), exports);
__exportStar(require("./build-type"), exports);
__exportStar(require("./c-type-map"), exports);
__exportStar(require("./class-details"), exports);
__exportStar(require("./config-flags"), exports);
__exportStar(require("./construct-name"), exports);
__exportStar(require("./dependency-map"), exports);
__exportStar(require("./dependency"), exports);
__exportStar(require("./environment"), exports);
__exportStar(require("./function-description"), exports);
__exportStar(require("./function-map"), exports);
__exportStar(require("./g-type"), exports);
__exportStar(require("./generate-config"), exports);
__exportStar(require("./gir-alias"), exports);
__exportStar(require("./gir-array"), exports);
__exportStar(require("./gir-boolean"), exports);
__exportStar(require("./gir-class"), exports);
__exportStar(require("./gir-construct"), exports);
__exportStar(require("./gir-doc"), exports);
__exportStar(require("./gir-enumeration"), exports);
__exportStar(require("./gir-enumeration-member"), exports);
__exportStar(require("./gir-implements"), exports);
__exportStar(require("./gir-include"), exports);
__exportStar(require("./gir-module-resolved-by"), exports);
__exportStar(require("./gir-modules-grouped-map"), exports);
__exportStar(require("./gir-modules-grouped"), exports);
__exportStar(require("./gir-namespace"), exports);
__exportStar(require("./gir-parameter"), exports);
__exportStar(require("./gir-prerequisite"), exports);
__exportStar(require("./gir-repository"), exports);
__exportStar(require("./gir-signal"), exports);
__exportStar(require("./gir-type"), exports);
__exportStar(require("./gir-variable"), exports);
__exportStar(require("./gir-virtual-method"), exports);
__exportStar(require("./inheritance-table"), exports);
__exportStar(require("./local-names"), exports);
__exportStar(require("./parsed-gir"), exports);
__exportStar(require("./resolve-type"), exports);
__exportStar(require("./sym-table"), exports);
__exportStar(require("./transformation-case"), exports);
__exportStar(require("./transformations"), exports);
__exportStar(require("./ts-for-gjs-extended"), exports);
__exportStar(require("./type-array-suffix"), exports);
__exportStar(require("./type-nullable-suffix"), exports);
__exportStar(require("./type-suffix"), exports);
__exportStar(require("./user-config-load-result"), exports);
__exportStar(require("./user-config"), exports);
//# sourceMappingURL=index.js.map